### ISSUE TITLE
Upgrade Ruby version

### ISSUE THREAD

**Issue by wslack** [18F/docker-ruby-ubuntu#6]
https://github.com/18F/docker-ruby-ubuntu/blob/master/Dockerfile is set to `2.3.1` and blocking builds set to `2.3.3`.

**Comment by brandocalrissian** [comment]
As a container/devops novice (only knowing general designs, not implementation), my questions would be:

1) If we update the Dockerfile to v2.3.3, does that trigger any security scan procedure for the changed environment? (I think yes.)
2) Are there any problems running builds set to earlier versions of ruby once we update our version? (I think no.)
3) Are there any reasons we shouldn't run ruby v2.3.3 in cloud.gov? (We're doing our own build/install, so I don't expect there to be any issues.)
4) How do we want to test this in staging to verify we don't break anything? (We'll probably build a couple of test apps as a sanity check.)

**Comment by wslack** [comment]
1. I think yes as well.
2. I think yes - we've had issues for others specifying old versions of Ruby.
3. Not that I know of.
4. Make sure 18f.gsa.gov can still build, try out some other apps.

I also want to figure out a better cadence for these updates and being aware if security ever makes one necessary.

**Comment by wslack** [comment]
Done!
